backbone=dict(
    type='MuSwinTransformer',
    embed_dim=96,
    depths=[2, 2, 18, 2],
    num_heads=[3, 6, 12, 24],
    window_size=7,
    mlp_ratio=4.,
    qkv_bias=True,
    qk_scale=None,
    drop_rate=0.,
    attn_drop_rate=0.,
    drop_path_rate=0.2,
    ape=False,  # if true, add absolute position embedding to patch embedding
    patch_norm=True,
    out_indices=(0, 1, 2, 3),
    use_checkpoint=False)
neck=dict(
    type='MuFPN',
    in_channels=[96, 192, 384, 768],
    out_channels=256,
    num_outs=5)